### ISSUE TITLE
docker: Error response from daemon: service endpoint with name already exists.

### ISSUE THREAD

**Issue by kodie** [zodern/meteor-up#478] opened 2017-02-20 18:24 UTC
Trying to deploy my Meteor app to a fresh DigitalOcean droplet. `mup setup` runs just fine but running `mup deploy` gives me this:

```
Started TaskList: Start Meteor
[123.456.78.910] - Start Meteor
[123.456.78.910] x Start Meteor: FAILED

	-----------------------------------STDERR-----------------------------------
	Error response from daemon: No such container: myapp-frontend
	Error response from daemon: No such container: myapp-nginx-letsencrypt
	Error response from daemon: No such container: myapp-nginx-proxy
	docker: Error response from daemon: service endpoint with name myapp already exists.
	-----------------------------------STDOUT-----------------------------------
	myapp
	Removed myapp-frontend
	Removed myapp-nginx-letsencrypt
	Removed myapp-nginx-proxy
	Using default tag: latest
	latest: Pulling from kadirahq/meteord
	Digest: sha256:7ec54d5fafc11acbcc82f3e555fddce8e4742ddeda05a64997f2a10e3c04137e
	Status: Image is up to date for kadirahq/meteord:latest
	Pulled kadirahq/meteord
	cd19e3ea19ef8e6042153e0e7da0af7ed07b3a4a916d251d62d4c30791ca0432
	----------------------------------------------------------------------------
(node:15428) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error:
-----------------------------------STDERR-----------------------------------
Error response from daemon: No such container: myapp-frontend
Error response from daemon: No such container: myapp-nginx-letsencrypt
Error response from daemon: No such container: myapp-nginx-proxy
docker: Error response from daemon: service endpoint with name myapp already exists.
-----------------------------------STDOUT-----------------------------------
myapp
Removed myapp-frontend
Removed myapp-nginx-letsencrypt
Removed myapp-nginx-proxy
Using default tag: latest
latest: Pulling from kadirahq/meteord
Digest: sha256:7ec54d5fafc11acbcc82f3e555fddce8e4742ddeda05a64997f2a10e3c04137e
Status: Image is up to date for kadirahq/meteord:latest
Pulled kadirahq/meteord
cd19e3ea19ef8e6042153e0e7da0af7ed07b3a4a916d251d62d4c30791ca0432
----------------------------------------------------------------------------
```

**Comment by lunatolun** [comment] 2017-02-20 21:40
+1

**Comment by zodern** [comment] 2017-02-21 16:28
In #448 there was a similar problem. I'm not able to reproduce this. Please post your mup.js file. Also, which image did you use for the droplet, what size is it, and did you select any of the additional options? Did you do anything on the droplet besides running `mup setup` and `mup deploy`?

**Comment by kodie** [comment] 2017-02-21 16:40
```javascript
module.exports = {
  servers: {
    one: {
      host: '123.456.78.910',
      username: 'root',
      // pem: '/home/user/.ssh/id_rsa',
      // password: 'password',
      // or leave blank to authenticate using ssh-agent
      opts: {
          //port: 22,
      },
    }
  },

  meteor: {
    name: 'myapp',
    path: '/www/apps/myapp',
    // docker: {
    //   image: 'abernix/meteord:base',
    // },
    servers: {
      one: {}
    },
    env: {
      ROOT_URL: 'http://myapp.mysite.com',
      MONGO_URL: '[MY MONGO STUFF]'
    },
    deployCheckWaitTime: 120,
    enableUploadProgressBar: true
  },

  mongo: {
    oplog: true,
    port: 10369,
    version: '3.4.1',
    servers: {
      one: {}
    },
  },
};
```

Droplet:
512 MB Memory / 20 GB Disk / NYC3 - Ubuntu 16.04.1 x64 w/ IPv6 enabled

Haven't done anything besides mup setup and mup deploy. Even tried destroying the droplet and remaking it and got the same results.

**Comment by lunatolun** [comment] 2017-02-21 22:37
Mine is Ubuntu 14.04 x64 
dockerImage: 'abernix/meteord:base'
deployCheckWaitTime: 120 (always worked fine)

As it was mentioned in issue [#448](https://github.com/zodern/meteor-up/issues/448) when I first did setup and deploy, it worked with Dogfalo/Materialize 0.97 but when I tried with 0.98 it didn't work and the next deploys also didn't work, no matter what I change. I didn't try a fresh install with 0.97 yet but I'm pretty sure it will fix the problem. I'll write an update when I try. Probably tonight or tomorrow

**Comment by lunatolun** [comment] 2017-02-23 20:34
Fresh install on Ubuntu 14.04.5 x64, Dogfalo/Materialize v0.97 works like a charm, including SSL.

**Comment by Twisterking** [comment] 2017-02-24 22:43
+1

Same problem here!
Fresh droplet with 512MB RAM on Ubuntu 16.04 X64.
mup.js:
```
module.exports = {
  servers: {
    test: {
      host: '111.111.111.111',
      username: 'root',
      pem: '~/.ssh/id_rsa'
    }
  },
  meteor: {
    name: 'myapp',
    path: '../../app',
    volumes: {
      '/opt/myapp': '/files',
      '/usr/share/zoneinfo/Europe/Vienna': '/etc/localtime:ro',
      '/usr/share/zoneinfo': '/usr/share/zoneinfo:ro',
      '/etc/timezone': '/etc/timezone:ro',
    },
    docker: {
      image: 'abernix/meteord:base'
    },
    servers: {
      test: {}
    },
    buildOptions: {
      serverOnly: true,
      debug: true,
      cleanAfterBuild: true,
    },
    env: {
      ROOT_URL: 'https://dev.myapp.at',
      PORT: 80,
      NODE_ENV: 'test'
    },
    ssl: {
      crt: './fullchain_dev.pem',
      key: './privkey_dev.pem',
      port: 443
    },
    deployCheckWaitTime: 45,
    enableUploadProgressBar: false
  },
  mongo: {
    oplog: false,
    port: 27017,
    // version: '3.4.1',
    servers: {
      test: {}
    }
  }
};
```

What is your guess? Maybe trying Ubuntu 14.04 instead and see if that changes anything?!

**Comment by kodie** [comment] 2017-02-24 23:02
Can confirm that like @lunatolun, a fresh install on Ubuntu 14.04.5 x64 works.

**Comment by Twisterking** [comment] 2017-02-24 23:19
OK ... rebuilt my droplet with 14.04 x64 and now I have some new problems! 👎  https://github.com/zodern/meteor-up/issues/493

**Comment by Cu4rach4** [comment] 2017-03-01 14:30
can you exec free to see you swap?, jus t add a new swapfile to your linux and should be work...

You will see something like this:

> free
              total        used        free      shared  buff/cache   available
Mem:        1014372      149508       57048       12192      807816      804136
Swap:       2097148       41760     2055388

**Comment by joaolboing** [comment] 2017-03-06 17:23
This seems to be a docker bug.
When the container is removed, docker sometimes can't disconnect the container from the network
I run on the server:
```
docker network disconnect bridge "AppName" -f
```
Then I can deploy normally

What can be done is to update the startup script to include the command above after the 'docker rm -f AppName'

**Comment by Twisterking** [comment] 2017-03-06 17:40
@Cu4rach4 My Swap is pretty much empty, about 3.5 GB free! ;)
@joaolboing thanks for that input! I trust you on this and integrate this and make a PR as this seems totally resonable!
EDIT: Just saw you already created a PR! Thanks!

**Comment by shadowcodex** [comment] 2017-03-06 20:56
PR Merged.

**Closed as completed by shadowcodex** 2017-03-06 20:56 UTC
Labels: Bug

**Comment by zodern** [comment] 2017-03-07 14:49
I encountered this error for the first time today, and the PR fixed it.
