### ISSUE TITLE
env.MONGO_URL changes are not affected

### ISSUE THREAD

**Issue by hanimay** [zodern/meteor-up#1067] opened 2019-03-14 11:16 UTC
Mup version (1.4.5):

env.MONGO_URL changes are not affected.
I tried reconfig, deploy, setup...
it only takes the initial value and later changes are reflected.

**Comment by zodern** [comment] 2019-03-14 14:16
You need to remove the `mongo` object from your config: http://meteor-up.com/docs#external-database. When the `mongo` object is in your config, it overwrites `env.MONGO_URL` to the correct value for the built-in database.

**Comment by hanimay** [comment] 2019-03-15 11:04
I'm not using an external database, I simply want to rename the database.
that's the format I have, so I wrote the database name wrongly the first time and now I'm stuck can't rename it, so I had to and rename the database inside of mongo to suit the name I wrote first in the config file.
  app: {
 .....
    env: {
      ROOT_URL: 'https://aaa.com/',
      MONGO_URL: 'mongodb://localhost/DATABASE_NAME'
    },
.....

**Comment by elie222** [comment] 2019-03-21 18:35
I've been seeing the same thing today. No idea what changed, but I'm also on Mup 1.4.5. I'm trying to change a different env var in my app. Nothing to do with Mongo.

**Comment by elie222** [comment] 2019-03-21 18:38
Actually have no idea where the issue is, because I've been using 1.4.5 fine for the last 6 months+. This is a new server, but removing the env var doesn't seem to work.

**Comment by zodern** [comment] 2019-03-21 19:07
`mup reconfig` in 1.4.5 is not able to remove environment variables that were set during the last deploy. You should use `mup deploy` to remove them. This will be fixed in 1.5.

**Comment by elie222** [comment] 2019-03-21 19:23
I also tried mup deploy. Will try again now.

**Closed as completed** 2019-04-21 22:46 UTC
