### ISSUE TITLE
Deployment fails with exit error 254 !!!!

### ISSUE THREAD

**Issue by mokaid** [zodern/meteor-up#642] opened 2017-06-12 20:13 UTC
Hello ... 

Any suggestion  ... ?
Whats wrong with sshpk package, I check the json package file inside sshpk folder the slashes are in their right direction , what else should I check ?

 Verifying Deployment: FAILED

 > mup logs --tail=50

[xx.xx.xx.xx]npm ERR! Please include the following file with any support request:
[xx.xx.xx.xx]npm ERR!     /bundle/bundle/programs/server/npm-debug.log
[xx.xx.xx.xx]> meteor-dev-bundle@0.0.0 install /bundle/bundle/programs/server
[xx.xx.xx.xx]> node npm-rebuild.js
[xx.xx.xx.xx]npm ERR! Linux 4.4.0-78-generic
[xx.xx.xx.xx]npm ERR! argv "/opt/nodejs/bin/node" "/opt/nodejs/bin/npm" "rebuild" "--update-binary"
[xx.xx.xx.xx]npm ERR! node v4.8.0
[xx.xx.xx.xx]npm ERR! npm  v3.10.10
[xx.xx.xx.xx]npm ERR! path /bundle/bundle/programs/server/npm/node_modules/meteor/npm-container/node_modules/sshpk/bin\sshpk-conv
[xx.xx.xx.xx]npm ERR! code ENOENT
[xx.xx.xx.xx]npm ERR! errno -2
[xx.xx.xx.xx]npm ERR! syscall chmod
[xx.xx.xx.xx]npm ERR! enoent ENOENT: no such file or directory, chmod '/bundle/bundle/programs/server/npm/node_modules/meteor/npm-container/node_modules/sshpk/bin\sshpk-conv'
[xx.xx.xx.xx]npm ERR! enoent ENOENT: no such file or directory, chmod '/bundle/bundle/programs/server/npm/node_modules/meteor/npm-container/node_modules/sshpk/bin\sshpk-conv'
[xx.xx.xx.xx]npm ERR! enoent This is most likely not a problem with npm itself
[xx.xx.xx.xx]npm ERR! enoent and is related to npm not being able to find a file.
[xx.xx.xx.xx]npm ERR! enoent
[xx.xx.xx.xx]npm ERR! Please include the following file with any support request:
[xx.xx.xx.xx]npm ERR!     /bundle/bundle/programs/server/npm/node_modules/meteor/npm-container/npm-debug.log
[xx.xx.xx.xx]npm WARN meteor-dev-bundle@0.0.0 No description
[xx.xx.xx.xx]npm WARN meteor-dev-bundle@0.0.0 No repository field.
[xx.xx.xx.xx]npm WARN meteor-dev-bundle@0.0.0 No license field.
[xx.xx.xx.xx]npm ERR! Linux 4.4.0-78-generic
[xx.xx.xx.xx]npm ERR! argv "/opt/nodejs/bin/node" "/usr/bin/npm" "install" "--unsafe-perm"
[xx.xx.xx.xx]npm ERR! node v4.8.0
[xx.xx.xx.xx]npm ERR! npm  v3.10.10
[xx.xx.xx.xx]npm ERR! code ELIFECYCLE
[xx.xx.xx.xx]npm ERR! meteor-dev-bundle@0.0.0 install: `node npm-rebuild.js`
[xx.xx.xx.xx]npm ERR! Exit status 254
[xx.xx.xx.xx]npm ERR!
[xx.xx.xx.xx]npm ERR! Failed at the meteor-dev-bundle@0.0.0 install script 'node npm-rebuild.js'.
[xx.xx.xx.xx]npm ERR! Make sure you have the latest version of node.js and npm installed.
[xx.xx.xx.xx]npm ERR! If you do, this is most likely a problem with the meteor-dev-bundle package,
[xx.xx.xx.xx]npm ERR! not with npm itself.
[xx.xx.xx.xx]npm ERR! Tell the author that this fails on your system:
[xx.xx.xx.xx]npm ERR!     node npm-rebuild.js
[xx.xx.xx.xx]npm ERR! You can get information on how to open an issue for this project with:
[xx.xx.xx.xx]npm ERR!     npm bugs meteor-dev-bundle
[xx.xx.xx.xx]npm ERR! Or if that isn't available, you can get their info via:
[xx.xx.xx.xx]npm ERR!     npm owner ls meteor-dev-bundle
[xx.xx.xx.xx]npm ERR! There is likely additional logging output above.
[xx.xx.xx.xx]npm ERR! Please include the following file with any support request:
[xx.xx.xx.xx]npm ERR!     /bundle/bundle/programs/server/npm-debug.log

        ----------------------------------------------------------------------------

**Comment by zodern** [comment] 2017-09-16 02:11
Duplicate of #531.

**Closed as completed by zodern** 2017-09-16 02:11 UTC

**Comment by Meeta-motherfds** [comment] 2022-07-03 13:56
Now Error code 254 is fixed or not?

I got an error 254 , what should I do?
Any suggestion...
