### ISSUE TITLE
Tear down docker container after failed SSL check

### ISSUE THREAD

**Issue by subhog** [zodern/meteor-up#606] opened 2017-05-11 12:08 UTC
I did a new ssl setup but used a wrong private key file (I'm cleaning a mess in our keys folder). During another trial, I got a message saying that the container name `***-dummy-http-server-for-ssl-check` is already in use:

    x Verifying SSL Configurations: FAILED
	
	-----------------------------------STDERR-----------------------------------
	docker: Error response from daemon: Conflict. The container name "/***-dummy-http-server-for-ssl-check" is already in use by container ***. You have to remove (or rename) that container to be able to reuse that name..
	See 'docker run --help'.
	nginx: [emerg] SSL_CTX_use_PrivateKey_file("/private.key") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
	nginx: configuration file /opt/nginx/conf/nginx.conf test failed
	-----------------------------------STDOUT-----------------------------------
	----------------------------------------------------------------------------

Looks like the test container is not stopped if SSL test fails.

**Comment by zodern** [comment] 2017-06-03 20:33
Duplicate of #205

**Closed as completed by zodern** 2017-06-03 20:33 UTC
Labels: Bug, SSL
