### ISSUE TITLE
mup 1.3.1 deploys to different location on server?

### ISSUE THREAD

**Issue by mcsimenc** [zodern/meteor-up#716] opened 2017-08-30 17:16 UTC
I upgraded from mup 1.2.11 to 1.3.1. Then I redeployed a new version of my app and discovered that /opt came to have only **edit: three** subdirectories, /opt/app/tmp and /opt/app/certs and /opt/app/config. I needed to know where the app was deployed to so I could link to binaries on the server. The app was accessible on the web but I but couldn't find the actual location of it on the server. So I downgraded to 1.2.11 and redeployed and got the app back in /opt/app/current.

So this might not even be an issue and it's just that I don't know where the v1.3.1-deployed app was going. Thanks :)

**Comment by amanagarwal2189** [comment] 2017-08-30 17:48
isnt it in /bundle/bundle?

**Comment by mcsimenc** [comment] 2017-08-30 17:56
Hmm no /bundle exists on my server now after redeployment with v1.2.11 but it's possible that place existed when I deployed with v1.3.1.   v1.2.11 puts my app in /opt/app/current/bundle.

Sorry I was wrong about which directories the v1.3.1 deployment created, it created:
```
/opt/app/
        |_certs/
        |_config/
        |_tmp/

whereas v1.2.11 created:

/opt/app/
        |_certs/
        |_config/
        |_tmp/
        |_current/
        |_last/
```

**Comment by zodern** [comment] 2017-08-30 18:00
Duplicate of #710.

**Closed as completed by zodern** 2017-08-30 18:00 UTC
