### ISSUE TITLE
Second deployments fails and all the sites in the server goes down

### ISSUE THREAD

**Issue by asela-wijesinghe** [zodern/meteor-up#635] opened 2017-06-07 07:20 UTC
deployed the application using same `mup.js` settings 1st time, but the second deployment failed using `mup deploy` and all the sites in the server are down also
i have attached the file for reviewing.can someone point me to right direction please?

![image](https://user-images.githubusercontent.com/23404276/26866767-4787750c-4b80-11e7-965c-eae568335998.png)

```
module.exports = {
  servers: {
    one: {
      host: '172.104.48.74',
      username: 'uh39sleafy',
      pem: '.keys/LCProdSRV1.pem',
      opts: {
        port: 6781,
      }
      // pem:
      // password:
      // or leave blank for authenticate from ssh-agent
    }
  },

  meteor: {
    name: 'slmunFrontEnd',
    path: '/home/pubudu/Projects/slmun-frontend',
    // port: 3320,
    servers: {
      one: {},
    },
    buildOptions: {
      serverOnly: true,
    },
    env: {
      ROOT_URL: 'https://slmun.org',
      MONGO_URL: 'mongodb://lcsrv1slmun:M9LO1IH8420589R0qfw2pLWbaOvH84A0p7c9kd5z@ds019488.mlab.com:19488/lcsrv1-slmunmcdb',
      PORT: 3320
    },


    docker: {
      // change to 'kadirahq/meteord' if your app is not using Meteor 1.4
      image: 'abernix/meteord:base',
    },
    deployCheckWaitTime: 600,

    // Show progress bar while uploading bundle to server
    // You might need to disable it on CI servers
    enableUploadProgressBar: true
  },
};

```

**Comment by THPubs** [comment] 2017-06-09 08:44
It's happening all the time even for me!

**Comment by albertonaperijr** [comment] 2017-06-09 10:31
It's happening when your deployed meteor app/s are connected/using the same/default mongodb database.

**Comment by THPubs** [comment] 2017-06-09 11:25
@albertonaperijr How can I fix it? I have two apps which need to rely on the same database (MLab).

**Comment by zodern** [comment] 2017-08-14 21:58
Duplicate of #260

**Closed as completed by zodern** 2017-08-14 21:58 UTC
