### ISSUE TITLE
Mup Deploy failed at Prepare Bundle

### ISSUE THREAD

**Issue by fhackenb** [zodern/meteor-up#835] opened 2017-12-12 20:53 UTC
I was getting some other MUP errors so I updated my mup and my latest error is on mup deploy is:

Started TaskList: Pushing Meteor App
[34.231.183.239] - Pushing Meteor App Bundle to the Server
[34.231.183.239] - Pushing Meteor App Bundle to the Server: SUCCESS
[34.231.183.239] - Prepare Bundle
[34.231.183.239] x Prepare Bundle: FAILED

        -----------------------------------STDERR-----------------------------------
        The command '/bin/sh -c cd  /built_app/programs/server &&     npm install --unsafe-perm' returned a non-zero code: 1
        -----------------------------------STDOUT-----------------------------------
        orm and node version. If you
        would like to compile fibers on this machine please make sure you have setup your
        build environment--
        Windows + OS X instructions here: https://github.com/nodejs/node-gyp
        Ubuntu users please run: `sudo apt-get install g++`
        Alpine users please run: `sudo apk add python make g++`
        sh: 1: nodejs: not found
        npm WARN meteor-dev-bundle@0.0.0 No description
        npm WARN meteor-dev-bundle@0.0.0 No repository field.
        npm WARN meteor-dev-bundle@0.0.0 No license field.

        npm ERR! file sh
        npm ERR! code ELIFECYCLE
        npm ERR! errno ENOENT
        npm ERR! syscall spawn
        npm ERR! fibers@1.0.13 install: `node build.js || nodejs build.js`
        npm ERR! spawn ENOENT
        npm ERR! 
        npm ERR! Failed at the fibers@1.0.13 install script.
        npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

        npm ERR! A complete log of this run can be found in:
        npm ERR!     /root/.npm/_logs/2017-12-12T20_43_06_523Z-debug.log
        loopleague-prod
        ----------------------------------------------------------------------------

My mup.js looks like:

module.exports = {
  servers: {
    one: {
      // TODO: set host address, username, and authentication method
      host: '34.231.183.239',
      username: 'ubuntu',
      pem: '../loopleague.pem'
      // password: 'server-password'
      // or neither for authenticate from ssh-agent
    }
  },

  meteor: {
    // TODO: change app name and path
    name: 'loopleague-prod',
    path: '../',

    servers: {
      one: {},
    },

    buildOptions: {
      serverOnly: true,
    },

    env: {
      PORT: 6666,    
      MAIL_URL: 'smtp://contact@loopleague.com:LoopLeague2017@smtp.gmail.com:465',
      ROOT_URL: 'http://app.loopleague.com',// //'http://app.loopleague.com', //'http://loopleague.racknersolutions.com',//
      MONGO_URL: 'mongodb://admin:LoopLeague2017@ds147870-a0.mlab.com:47870/loopleague-prod'
    },

    // ssl: { // (optional)
    //   // Enables let's encrypt (optional)
    //   autogenerate: {
    //     email: 'email.address@domain.com',
    //     // comma separated list of domains
    //     domains: 'website.com,www.website.com'
    //   }
    // },

    docker: {
      // change to 'abernix/meteord:base' if your app is using Meteor 1.4 - 1.5
      image: 'abernix/meteord:node-8.4.0-base',
    },

    // Show progress bar while uploading bundle to server
    // You might need to disable it on CI servers
    enableUploadProgressBar: true
  },

  mongo: {
    version: '3.4.1',
    servers: {
      one: {}
    }
  }
};

**Comment by fhackenb** [comment] 2017-12-12 21:04
I saw on another post that you suggested setting prepareBundle to false, so I tried that and now it's failing on the Verifying Deployment stage:

Started TaskList: Start Meteor
[34.231.183.239] - Start Meteor
[34.231.183.239] - Start Meteor: SUCCESS
[34.231.183.239] - Verifying Deployment
[34.231.183.239] x Verifying Deployment: FAILED

        -----------------------------------STDERR-----------------------------------
        ted platform and node version. If you
        would like to compile fibers on this machine please make sure you have setup your
        build environment--
        Windows + OS X instructions here: https://github.com/nodejs/node-gyp
        Ubuntu users please run: `sudo apt-get install g++`
        Alpine users please run: `sudo apk add python make g++`
        sh: 1: nodejs: not found
        npm WARN meteor-dev-bundle@0.0.0 No description
        npm WARN meteor-dev-bundle@0.0.0 No repository field.
        npm WARN meteor-dev-bundle@0.0.0 No license field.

        npm ERR! file sh
        npm ERR! code ELIFECYCLE
        npm ERR! errno ENOENT
        npm ERR! syscall spawn
        npm ERR! fibers@1.0.13 install: `node build.js || nodejs build.js`
        npm ERR! spawn ENOENT
        npm ERR! 
        npm ERR! Failed at the fibers@1.0.13 install script.
        npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

        npm ERR! A complete log of this run can be found in:
        npm ERR!     /root/.npm/_logs/2017-12-12T21_02_14_262Z-debug.log
         
        => Redeploying previous version of the app
         
        -----------------------------------STDOUT-----------------------------------

        To see more logs type 'mup logs --tail=100'

        ----------------------------------------------------------------------------

**Comment by fhackenb** [comment] 2017-12-12 21:09
With --verbose I'm getting:

Started TaskList: Pushing Meteor App
[34.231.183.239] - Pushing Meteor App Bundle to the Server
[34.231.183.239] - Pushing Meteor App Bundle to the Server: SUCCESS
[34.231.183.239] - Prepare Bundle
Error: No such image: mup-loopleague-prod:latest
[34.231.183.239] - Prepare Bundle: SUCCESS

Started TaskList: Configuring App
[34.231.183.239] - Pushing the Startup Script
[34.231.183.239] - Pushing the Startup Script: SUCCESS
[34.231.183.239] - Sending Environment Variables
[34.231.183.239] - Sending Environment Variables: SUCCESS

Started TaskList: Start Meteor
[34.231.183.239] - Start Meteor
Error: No such image: mup-loopleague-prod:latest
using bundle
Error: No such image: mup-loopleague-prod:previous
Error: No such image: mup-loopleague-prod:previous
Error: No such image: mup-loopleague-prod:latest
Image abernix/meteord:node-8.4.0-base
Volume --volume=/opt/loopleague-prod/current:/bundle
Removing docker containers. Errors about nonexistent endpoints and containers are normal.
loopleague-prod
Error response from daemon: endpoint loopleague-prod not found
Error: No such container: loopleague-prod-frontend
Error response from daemon: endpoint loopleague-prod-frontend not found
Error: No such container: loopleague-prod-nginx-letsencrypt
Error response from daemon: endpoint loopleague-prod-nginx-letsencrypt not found
Error: No such container: loopleague-prod-nginx-proxy
Error response from daemon: endpoint loopleague-prod-nginx-proxy not found
Finished removing docker containers
node-8.4.0-base: Pulling from abernix/meteord
Digest: sha256:04f44cf999da383d11de77027ced8b70818222c9890a405ce10803af3ee5a642
Status: Image is up to date for abernix/meteord:node-8.4.0-base
Pulled abernix/meteord:node-8.4.0-base
83dbe2b6291ca0a9b3eccd42f6c73481d1917741b1df6196a7dcb04e09dce66b
Ran abernix/meteord:node-8.4.0-base
[34.231.183.239] - Start Meteor: SUCCESS
[34.231.183.239] - Verifying Deployment
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) Recv failure: Connection reset by peer
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) Recv failure: Connection reset by peer
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (52) Empty reply from server
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) Recv failure: Connection reset by peer
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) Recv failure: Connection reset by peer
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) Recv failure: Connection reset by peer
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) Recv failure: Connection reset by peer
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (52) Empty reply from server
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) Recv failure: Connection reset by peer
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) Recv failure: Connection reset by peer
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) Recv failure: Connection reset by peer
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) Recv failure: Connection reset by peer
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) Recv failure: Connection reset by peer
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (52) Empty reply from server
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) Recv failure: Connection reset by peer
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) Recv failure: Connection reset by peer
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) Recv failure: Connection reset by peer
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) Recv failure: Connection reset by peer
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) Recv failure: Connection reset by peer
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) Recv failure: Connection reset by peer
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) Recv failure: Connection reset by peer
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) Recv failure: Connection reset by peer
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 6666: Connection refused
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (52) Empty reply from server
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) Recv failure: Connection reset by peer
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) Recv failure: Connection reset by peer
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) Recv failure: Connection reset by peer
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) Recv failure: Connection reset by peer
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) Recv failure: Connection reset by peer
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) Recv failure: Connection reset by peer
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) Recv failure: Connection reset by peer
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) Recv failure: Connection reset by peer
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 6666: Connection refused
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (56) Recv failure: Connection reset by peer
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) Recv failure: Connection reset by peer
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) Recv failure: Connection reset by peer
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) Recv failure: Connection reset by peer
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) Recv failure: Connection reset by peer
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) Recv failure: Connection reset by peer
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) Recv failure: Connection reset by peer
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) Recv failure: Connection reset by peer
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 6666: Connection refused
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 6666: Connection refused
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 6666: Connection refused
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) Recv failure: Connection reset by peer
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) Recv failure: Connection reset by peer
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) Recv failure: Connection reset by peer
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (52) Empty reply from server
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) Recv failure: Connection reset by peer
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) Recv failure: Connection reset by peer
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) Recv failure: Connection reset by peer
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) Recv failure: Connection reset by peer
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) Recv failure: Connection reset by peer
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 6666: Connection refused
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 6666: Connection refused
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 6666: Connection refused
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 6666: Connection refused
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 6666: Connection refused
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 6666: Connection refused
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) Recv failure: Connection reset by peer
                                  ^
../src/fibers.cc:49:50: error: expected ',' or '...' before '<' token
  void WeakCallbackShim(const v8::WeakCallbackData<T, P>& data) {
                                                  ^
../src/fibers.cc: In function 'void uni::WeakCallbackShim(int)':
../src/fibers.cc:50:5: error: 'data' was not declared in this scope
   F(data.GetParameter());
     ^
../src/fibers.cc: In function 'v8::Handle<v8::String> uni::NewLatin1String(v8::Isolate*, const char*)':
../src/fibers.cc:102:64: warning: 'static v8::Local<v8::String> v8::String::NewFromOneByte(v8::Isolate*, const uint8_t*, v8::String::NewStringType, int)' is deprecated (declared at /root/.node-gyp/8.4.0/include/node/v8.h:2624): Use maybe version [-Wdeprecated-declarations]
   return String::NewFromOneByte(isolate, (const uint8_t*)string);
                                                                ^
../src/fibers.cc: In function 'v8::Handle<v8::String> uni::NewLatin1Symbol(v8::Isolate*, const char*)':
../src/fibers.cc:106:64: warning: 'static v8::Local<v8::String> v8::String::NewFromOneByte(v8::Isolate*, const uint8_t*, v8::String::NewStringType, int)' is deprecated (declared at /root/.node-gyp/8.4.0/include/node/v8.h:2624): Use maybe version [-Wdeprecated-declarations]
   return String::NewFromOneByte(isolate, (const uint8_t*)string);
                                                                ^
../src/fibers.cc: In static member function 'static uni::FunctionType Fiber::New(const Arguments&)':
../src/fibers.cc:423:99: warning: 'v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const' is deprecated (declared at /root/.node-gyp/8.4.0/include/node/v8.h:3787): Use maybe version [-Wdeprecated-declarations]
     return uni::Return(uni::Deref(Isolate::GetCurrent(), tmpl)->GetFunction()->NewInstance(1, argv), args);
                                                                                                   ^
../src/fibers.cc: In static member function 'static void Fiber::RunFiber(void**)':
../src/fibers.cc:611:14: warning: 'v8::TryCatch::TryCatch()' is deprecated (declared at /root/.node-gyp/8.4.0/include/node/v8.h:8157): Use isolate version [-Wdeprecated-declarations]
     TryCatch try_catch;
              ^
../src/fibers.cc: In static member function 'static void Fiber::SetPoolSize(v8::Local<v8::String>, v8::Local<v8::Value>, const SetterCallbackInfo&)':
../src/fibers.cc:731:43: warning: 'v8::Local<v8::Number> v8::Value::ToNumber() const' is deprecated (declared at /root/.node-gyp/8.4.0/include/node/v8.h:9578): Use maybe version [-Wdeprecated-declarations]
    Coroutine::pool_size = value->ToNumber()->Value();
                                           ^
../src/fibers.cc: In static member function 'static void Fiber::Init(v8::Handle<v8::Object>)':
../src/fibers.cc:785:72: warning: 'bool v8::Object::SetAccessor(v8::Local<v8::String>, v8::AccessorGetterCallback, v8::AccessorSetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute)' is deprecated (declared at /root/.node-gyp/8.4.0/include/node/v8.h:3120): Use maybe version [-Wdeprecated-declarations]
    fn->SetAccessor(uni::NewLatin1Symbol(isolate, "current"), GetCurrent);
                                                                        ^
../src/fibers.cc:786:87: warning: 'bool v8::Object::SetAccessor(v8::Local<v8::String>, v8::AccessorGetterCallback, v8::AccessorSetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute)' is deprecated (declared at /root/.node-gyp/8.4.0/include/node/v8.h:3120): Use maybe version [-Wdeprecated-declarations]
    fn->SetAccessor(uni::NewLatin1Symbol(isolate, "poolSize"), GetPoolSize, SetPoolSize);
                                                                                       ^
../src/fibers.cc:787:84: warning: 'bool v8::Object::SetAccessor(v8::Local<v8::String>, v8::AccessorGetterCallback, v8::AccessorSetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute)' is deprecated (declared at /root/.node-gyp/8.4.0/include/node/v8.h:3120): Use maybe version [-Wdeprecated-declarations]
    fn->SetAccessor(uni::NewLatin1Symbol(isolate, "fibersCreated"), GetFibersCreated);
                                                                                    ^
../src/fibers.cc: In instantiation of 'void uni::MakeWeak(v8::Isolate*, v8::Persistent<T>&, P*) [with void (* F)(void*) = Fiber::WeakCallback; T = v8::Object; P = void]':
../src/fibers.cc:341:60:   required from here
../src/fibers.cc:55:3: error: no matching function for call to 'v8::Persistent<v8::Object>::SetWeak(void*&, <unresolved overloaded function type>)'
   handle.SetWeak(val, WeakCallbackShim<F>);
   ^
../src/fibers.cc:55:3: note: candidates are:
In file included from /root/.node-gyp/8.4.0/include/node/node.h:63:0,
                 from ../src/coroutine.h:1,
                 from ../src/fibers.cc:1:
/root/.node-gyp/8.4.0/include/node/v8.h:544:18: note: template<class P> void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = P; T = v8::Object]
   V8_INLINE void SetWeak(P* parameter,
                  ^
/root/.node-gyp/8.4.0/include/node/v8.h:544:18: note:   template argument deduction/substitution failed:
../src/fibers.cc:55:3: note:   candidate expects 3 arguments, 2 provided
   handle.SetWeak(val, WeakCallbackShim<F>);
   ^
In file included from /root/.node-gyp/8.4.0/include/node/node.h:63:0,
                 from ../src/coroutine.h:1,
                 from ../src/fibers.cc:1:
/root/.node-gyp/8.4.0/include/node/v8.h:555:18: note: void v8::PersistentBase<T>::SetWeak() [with T = v8::Object]
   V8_INLINE void SetWeak();
                  ^
/root/.node-gyp/8.4.0/include/node/v8.h:555:18: note:   candidate expects 0 arguments, 2 provided
make: *** [Release/obj.target/fibers/src/fibers.o] Error 1
fibers.target.mk:102: recipe for target 'Release/obj.target/fibers/src/fibers.o' failed
make: Leaving directory '/bundle/bundle/programs/server/node_modules/fibers/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/nodejs/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-1041-aws
gyp ERR! command "/opt/nodejs/bin/node" "/opt/nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /bundle/bundle/programs/server/node_modules/fibers
gyp ERR! node -v v8.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++`
Alpine users please run: `sudo apk add python make g++`
sh: 1: nodejs: not found
npm WARN meteor-dev-bundle@0.0.0 No description
npm WARN meteor-dev-bundle@0.0.0 No repository field.
npm WARN meteor-dev-bundle@0.0.0 No license field.

npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! fibers@1.0.13 install: `node build.js || nodejs build.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the fibers@1.0.13 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-12-12T21_08_51_855Z-debug.log

To see more logs type 'mup logs --tail=100'

 
=> Redeploying previous version of the app
 
[34.231.183.239] x Verifying Deployment: FAILED

        -----------------------------------STDERR-----------------------------------
        ted platform and node version. If you
        would like to compile fibers on this machine please make sure you have setup your
        build environment--
        Windows + OS X instructions here: https://github.com/nodejs/node-gyp
        Ubuntu users please run: `sudo apt-get install g++`
        Alpine users please run: `sudo apk add python make g++`
        sh: 1: nodejs: not found
        npm WARN meteor-dev-bundle@0.0.0 No description
        npm WARN meteor-dev-bundle@0.0.0 No repository field.
        npm WARN meteor-dev-bundle@0.0.0 No license field.

        npm ERR! file sh
        npm ERR! code ELIFECYCLE
        npm ERR! errno ENOENT
        npm ERR! syscall spawn
        npm ERR! fibers@1.0.13 install: `node build.js || nodejs build.js`
        npm ERR! spawn ENOENT
        npm ERR! 
        npm ERR! Failed at the fibers@1.0.13 install script.
        npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

        npm ERR! A complete log of this run can be found in:
        npm ERR!     /root/.npm/_logs/2017-12-12T21_08_51_855Z-debug.log
         
        => Redeploying previous version of the app
         
        -----------------------------------STDOUT-----------------------------------

        To see more logs type 'mup logs --tail=100'

        ----------------------------------------------------------------------------

**Comment by devarthurribeiro** [comment] 2017-12-15 21:25
+1

**Comment by devarthurribeiro** [comment] 2017-12-15 21:29
This bug caused by bcrypt. @fhackenb post your mup.js file. I'm with the same error!

**Comment by derwaldgeist** [comment] 2018-03-14 13:26
+1 Is there a workaround?

**Comment by micahalcorn** [comment] 2018-04-19 15:47
This just recently started happening to me and I haven't changed my deployment process. Is it possible that we have all done something to our node environments?

**Comment by micahalcorn** [comment] 2018-04-19 15:59
For what it's worth, I noticed that when I `ssh`'d into my target machine manually, it was showing `*** System restart required ***`. Once I `reboot`ed it, everything works fine. 😕

**Comment by zodern** [comment] 2020-07-10 13:53
I am going to close this since the last comment was 2 years ago. If anyone encounters this error again, please create a new issue.

**Closed as completed by zodern** 2020-07-10 13:53 UTC
