### ISSUE TITLE
removing the mongo node from mup.js results in this error

### ISSUE THREAD

**Issue by reduxdj** [zodern/meteor-up#45] opened 2016-01-27 00:15 UTC
Not sure what's happened here... but if I set setupMongo: 0, and the remove the mongo node,  the setup still tries to install mongo

Setup Environment
TypeError: Cannot read property '_host' of undefined
    at Object.setup (index.js:33:15)
    at index.js:52:15
    at run (/Users/Patrick_/meteor-up/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:104:47)
    at /Users/Patrick_/meteor-up/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:115:28
    at flush (/Users/Patrick_/meteor-up/node_modules/babel-polyfill/node_modules/core-js/modules/$.microtask.js:19:5)
    at nextTickCallbackWith0Args (node.js:419:9)
    at process._tickCallback (node.js:348:13)

**Comment by madushan1000** [comment] 2016-01-27 04:36
This is a duplicate of issue https://github.com/kadirahq/meteor-up/issues/34, addressed by PR https://github.com/kadirahq/meteor-up/pull/41

**Closed as completed** 2016-01-27 09:11 UTC
