### ISSUE TITLE
Port Mapping 

### ISSUE THREAD

**Issue by ivanthemeh** [zodern/meteor-up#471] opened 2017-02-16 22:06 UTC
I am migrating to mup from mupx and when I was using mupx I was able to setup multiple meteor apps on a single server using the ports set uniquely. 
I am trying to set that up and it isnt working. The only way I can get the app to connect is by setting the meteor.env.PORT to 80 ```0.0.0.0:80->80/tcp``` otherwise it refuses to connect ```0.0.0.0:3001->80/tcp```.

I was just doing some more testing and have found out that if I go to mysite.com:3001 after setting the port to 3001 in meteor.env.PORT... so it seems like to me its setting it up backwards and exposing the docker to 3001 when it should be doing the app to 3001...am I right?

I am desparate and have been working on this for a while now. Im not a pro by any means but I can follow instructions from anyone who is willing to help me debug this and get it working. Thanks!

**Comment by maxmatthews** [comment] 2017-02-16 23:56
So I submitted a pull request (https://github.com/zodern/meteor-up/pull/472) for an update on the documentation, but I can confirm that it has to go in the `env` object with a key of `PORT` (all caps). Once you do that, it will run on the correct port. I was then able to set up nignx (and subsequently LetsEncrypt by hand/manually) and point it at the port I specified in `meteor.env.PORT`. 
@ivanthemeh Can you post your mup file? Also, let me know if you need assitance setting up nginx/apache. 
My `docker ps` looks like this, but I can confirm that outside the docker container, it is running on port `3005`:
```
a09fdfdc6a9b        abernix/meteord:base   "/bin/sh -c 'bash ..."   18 minutes ago      Up 18 minutes       0.0.0.0:3005->80/tcp         appName****
```

**Comment by ivanthemeh** [comment] 2017-02-16 23:59
@maxmatthews I can setup the nginx to do the port mapping myself I was just under the impression (and hoping) I wasnt going to have to do that.

**Comment by ivanthemeh** [comment] 2017-02-17 00:01
@maxmatthews 
```module.exports = {
  servers: {
    one: {
      host: '1.2.3.4',
      username: 'ubuntu',
      pem: '/location/to/pem'
      // password:
      // or leave blank for authenticate from ssh-agent
    }
  },

  meteor: {
    name: 'site',
    path: '/location/to/site',
    servers: {
      one: {},
    },
    buildOptions: {
      serverOnly: true,
    },
    env: {
      ROOT_URL: 'http://site.com',
      MONGO_URL: 'mongodb://localhost/meteor',
      PORT: 3000
    },

    // change to 'kadirahq/meteord' if your app is not using Meteor 1.4 else abernix/meteord:base
    // dockerImage: 'abernix/meteord:base',
    docker: {
       image: 'abernix/meteord:base', // change to 'kadirahq/meteord' if your app is not using Meteor 1.4
    },

    // ssl: {
    //   // Enables let's encrypt (optional)
    //   autogenerate: {
    //     email: 'me@me.com',
    //     domains: 'site.com' // comma seperated list of domains
    //   }
    // },

    deployCheckWaitTime: 60,

    // Show progress bar while uploading bundle to server
    // You might need to disable it on CI servers
    enableUploadProgressBar: true
  },

  mongo: {
    oplog: true,
    port: 27017,
    version: '3.4.1',
    servers: {
      one: {},
    },
  },
};```

**Comment by maxmatthews** [comment] 2017-02-17 00:02
You're trying to run multiple apps on the same server, right? If you are, you **will** have to set up nginx.

From the readme:
>**Multiple Deployments**
>Meteor Up supports multiple deployments to a single server. Meteor Up only does the deployment; if you need to configure subdomains, **you need to manually set up a reverse proxy yourself.**

**Comment by ivanthemeh** [comment] 2017-02-17 00:03
@maxmatthews whoops didnt see that..

**Comment by ivanthemeh** [comment] 2017-02-17 00:04
@maxmatthews you think if I do that its going to cause me to have to do the ssl manually?

**Comment by maxmatthews** [comment] 2017-02-17 00:05
Yea, that's how I did it. Just use `certbot`/`letsencrypt`, set up a crontab on your own, then drop the cert file paths into your nginx config. Happy to post my nginx config file if you need it. It's not ideal, but I think it's a bit out of scope of this project to have multiple deployments with SSL right now.

**Comment by ivanthemeh** [comment] 2017-02-17 01:09
@maxmatthews so I set up the nginx reverse proxy like I usually do and its still only connecting if I go to the site at port 3000? What the heck is going on?

**Comment by maxmatthews** [comment] 2017-02-17 01:22
@ivanthemeh Can you post your nginx config file?

**Comment by ivanthemeh** [comment] 2017-02-17 01:24
@maxmatthews 
```
server {
    listen                80;
    server_name           site.com;

    location / {
        proxy_pass http://127.0.0.1:3000;

        proxy_http_version 1.1;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_buffer_size          128k;
        proxy_buffers              4 256k;
        proxy_busy_buffers_size    256k;
    }
}
```

**Comment by ivanthemeh** [comment] 2017-02-17 01:39
@maxmatthews its like the port I set in env is the port I have to view the site at so If I set it to port 3000 the only way I can view the site is with site.com:3000 and when I set the reverse proxy up it doesnt change a thing.

**Comment by maxmatthews** [comment] 2017-02-17 01:41
When you hit site.com on port 80, do you get an nginx default welcome screen?

**Comment by ivanthemeh** [comment] 2017-02-17 01:48
@maxmatthews nope... connection refused.

**Comment by ivanthemeh** [comment] 2017-02-17 01:55
@maxmatthews were you able to get two sites on the same server working? Im about to give up on this its driving me nuts and Ive been working on it ALL DAY..

**Comment by ivanthemeh** [comment] 2017-02-17 02:08
@maxmatthews should I setup the proxy first?

**Comment by ivanthemeh** [comment] 2017-02-17 02:16
@maxmatthews I just tried setting it is still only available at site.com:3000 something is going on thats not supposed to be. It should be mapping the container to port 3000 and accepting port 80 traffic but its doing it the opposite. 
ANY HELP Please!

@zodern any ideas whats going on?

**Comment by maxmatthews** [comment] 2017-02-17 04:47
@ivanthemeh This may be against github protocol, but I reached out to you over email. Hopefully we'll be able to work it out offline and post the solution back here. However, if you'd prefer to keep it all within Github, we totally can. LMK!

**Comment by kandizzy** [comment] 2017-02-19 21:41
I have the exact same issue at the moment, if it's figured out will you post the solution here? Thanks!

**Comment by melkati** [comment] 2017-02-23 20:20
I have this issue also.

Do you have any solution for this?

**Comment by ivanthemeh** [comment] 2017-02-23 21:41
@kandizzy @melkati I was not able to figure this issue out. If either of you do let me know please 😄 
I just had to settle for deploying a single instance per server for now.

**Comment by kandizzy** [comment] 2017-02-24 01:05
@ivanthemeh i managed to get this working, however i'm not exactly sure which change I made was the one to do the trick. Here's everything I did though:
- removed `PORT` from `meteor.env` and set `meteor.port` to 3000
- added a `VIRTUAL_HOST` variable to `meteor.env` with the vhost name from my nginx conf
- upgraded this npm module locally with the changes from this [PR](https://github.com/zodern/meteor-up/pull/383)
- removed `meteor.dockerImage` and replaced it with `meteor.docker` which looks like this
```
docker: {
      image: 'abernix/spaceglue:node-4.6.2-builddeps',
      imagePort: 3000
    }
```

Now my docker container looks like this
```
abernix/spaceglue:node-4.6.2-builddeps   "/bin/sh -c ./run_..."   About an hour ago   Up About an hour    0.0.0.0:32770->3000/tcp
```
My nginx conf looks just like the one you pasted above and it works :)

**Closed as completed** 2017-03-06 17:40 UTC
