### ISSUE TITLE
How support chromedriver (java, webdriverio)?

### ISSUE THREAD

**Issue by thebarty** [zodern/meteor-up#821] opened 2017-11-29 09:06 UTC
Hi guys,

I am really a newbie on this topic.

My project uses `npm install webdriverio chromedriver`, it works locally on my macbook, BUT NOT in MUP-production.

It seems like there is NO java installed on the docker image I use `abernix/meteord:node-8.4.0-base`. At least a `docker exec mycontainer java` gives me an `executable file not found in $PATH`.

Now is this possible to do with MUP?
I have found some scripts to install chromedriver on ubuntu (https://gist.github.com/ziadoz/3e8ab7e944d02fe872c3454d17af31a5) - is there maybe a way to attach them somewhere?

**Comment by thebarty** [comment] 2017-11-29 09:13
Actually I think the npm chromedriver package should automatically install everything neccessary via npm. Let me research a bit more - if you have a quick tip: very welcome!

**Comment by zodern** [comment] 2018-02-22 14:17
@thebarty did you find a way to install chrome driver?

**Comment by zodern** [comment] 2018-03-28 19:56
I am going to close this as a duplicate of #362.

**Closed as completed by zodern** 2018-03-28 19:56 UTC
