### ISSUE TITLE
Error: ENAMETOOLONG: name too long

### ISSUE THREAD

**Issue by Rongky** [zodern/meteor-up#772] opened 2017-10-24 04:31 UTC
Doing either the ff: results to the above error...
1. mobileSettings: require('/path-to/settings.json')   or 
2. mobileSettings: {
        public: {
          settings1: {
            xxx: 'xxx',
            xxx: 'xxx',
            xxx: 'xxx'
          },
          settings2: {
            xxx: 'xxx',
            xxx: 'xxx',
          },
          settings3: 'xxx',
          settings4: 'xxx',
          settings5: 'xxx',
      },
  },

However, placing the mobile settings file (settings.json) at the root directory fix the issue. But this defeats the purpose of placing the settings.json inside the .deploy directory for mup.

**Comment by zodern** [comment] 2017-10-24 12:29
@Rongky could you please show the output of the command that has the error?

**Comment by Rongky** [comment] 2017-11-21 06:30
Sorry for the late reply... 
I'm also deploying to mobile and desktop using meteor-desktop package by wojtkowiak so I needed to set a separate mobileSettings file, although, mup settings.json and mobileSettings have the same content/settings.

using inside mup.js:
mobileSettings: require(' /home/rongky/app/.deploy/staging/settings.json')

command:
DEBUG=* mup deploy --verbose --settings /home/rongky/app/.deploy/staging/settings.json

here is the complete error:

[meteor-desktop]: Preparing desktop.asar took: 1997.124ms
/home/rongky/.meteor/packages/juliancwirko_postcss/.1.2.0.182ee2j++os+web.browser+web.cordova/plugin.minifier-postcss.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:190
      throw error;
      ^

Error: ENAMETOOLONG: name too long, open '{"xxxx":{"id":"xxxx"},"public":{"app":{"name":"appname","version":"0.3.7"},"connectionBanner":{"connectionLostText":"App is OFFLINE.","tryReconnectText":"Retry now...","reconnectBeforeCountdownText":"Attempting to reconnect in","reconnectAfterCountdownText":"s"},"staleSessionInactivityTimeout":180000,"staleSessionHeartbeatInterval":180000,"staleSessionPurgeInterval":60000,"staleSessionActivityEvents":"mousemove click keydown","cloudinary":{"cloud_name":"xxx","upload_preset":"xxx"}},"private":{}}'
    at Object.fs.openSync (fs.js:648:18)
    at Object.fs.readFileSync (fs.js:553:33)
    at Object.wrapper [as readFile] (/tools/fs/files.js:1558:35)
    at CordovaBuilder.copyWWW (/tools/cordova/builder.js:403:24)
    at CordovaProject.prepareFromAppBundle (/tools/cordova/project.js:204:13)
    at buildmessage.enterJob (/tools/cli/commands.js:1063:24)
    at /tools/utils/buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at main.captureAndExit (/tools/cli/commands.js:1052:20)
    at /tools/utils/buildmessage.js:271:13
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.main.captureAndExit (/tools/cli/main.js:274:29)
    at buildCommand (/tools/cli/commands.js:1042:10)
    at Command.func (/tools/cli/commands.js:876:12)
    at /tools/cli/main.js:1522:15

**Comment by zodern** [comment] 2019-04-21 20:46
I am going to close this as a duplicate of #929

**Closed as completed by zodern** 2019-04-21 20:46 UTC
Labels: Bug
