### ISSUE TITLE
Docker eats up all the space

### ISSUE THREAD

**Issue by PolGuixe** [zodern/meteor-up#479] opened 2017-02-20 21:00 UTC
Docker eats up all the space. After 2 months it grew up till it took all the space available. Specially the folder `/var/lib/docker/aufs`.

Is anyone experiencing problems of space in their deployments?

**Comment by zodern** [comment] 2017-02-20 22:39
This is a duplicate of #391.

**Closed as completed by zodern** 2017-02-20 22:39 UTC
