### ISSUE TITLE
Error while deploying multiple meteor apps

### ISSUE THREAD

**Issue by iAssureIT** [zodern/meteor-up#527] opened 2017-03-11 19:29 UTC
Hi,
I am trying to deploy multiple meteor apps on AWS Ubuntu server using Nginx. I am getting error while doing **mup deploy** for app#2. 
node v7.7.2
npm 4.1.2

**App#1**
My first app1 is working fine on site1. 
App#1, which is working fine, is using meteor PORT: 3000 and mongo PORT: 27017.

**App#2**
App#2, which is giving above error, is using meteor PORT: 3003 and mongo PORT: 27021. 
App#2 is giving following error . 

**mup deploy** error

```
 Build Error. Check the logs printed above.
(node:12934) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: build-error
(node:12934) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

mup.js file for app#2

```
module.exports = {
  servers: {
    one: {
      host: '35.164.201.159',
      username: 'ubuntu',
      pem: '~/.ssh/iAssureIT-Ubuntu.pem',
      // password:
      // or leave blank for authenticate from ssh-agent
    }
  },

  meteor: {
    name: 'musissive',
    path: '/var/www/meteor/musissive',
    servers: {
      one: {},
    },
    buildOptions: {
      serverOnly: true,
    },
    env: {
      ROOT_URL: 'http://musissive.in',
      MONGO_URL: 'mongodb://localhost:27021/meteor',
      PORT: 3003
    },


    docker: {
      // change to 'kadirahq/meteord' if your app is not using Meteor 1.4
      image: 'abernix/meteord:base',
    },
    deployCheckWaitTime: 60,

    // Show progress bar while uploading bundle to server
    // You might need to disable it on CI servers
    enableUploadProgressBar: false
  },

  mongo: {
    oplog: true,
    port: 27021,
    version: '3.4.1',
    servers: {
      one: {},
    },
  },
};
~
```

I was consistently getting the above error, even when mongo port was 27017 for both apps... So tried different ports for Mongodb in both apps. 
What must be causing the above error during **mup deploy**?

**Comment by zodern** [comment] 2017-03-12 02:43
If you are deploying both apps to the same server, the mongo port needs to be the same.

Please show more of the logs.

**Comment by ivanthemeh** [comment] 2017-03-12 16:43
@iAssureIT can you show that it is changing your ports in the docker config? Im having an issue with even SETTING the PORT... Anytime I change it its does nothing to the docker containers and givers me a error on deploy with no error messages and still deploys the app..
@zodern any ideas, Ive tried dropping the ssl and it still does absolutely nothing when I add env.PORT?

**Comment by zodern** [comment] 2017-03-12 17:41
@ivanthemeh at what step of the deploy process does it give you an error? If you run `docker ps` on the server, it should show something like ` 0.0.0.0:3000->80/tcp` under `PORTS`, where 3000 would be the port you set.

**Comment by ivanthemeh** [comment] 2017-03-12 17:44
@zodern it is showing me that but its not connecting at all, even when I setup the reverse proxy its not working.

**Comment by ivanthemeh** [comment] 2017-03-12 18:09
@zodern ok Ive got it working with two apps but my second app for some reason is a duplicate of the other one even though I deployed a different app..

**Comment by iAssureIT** [comment] 2017-03-12 18:22
@zodern,
I changed the mongo port to 27017 for both apps. 
Now my **mup deploy** command is hanging forever. It is not responding at all. 
I thought it must be issue with something else... So I did following

At project's root folder
```
rm -rf node_modules
npm cache clear
npm install
```

Again tried... Nothing worked.. 
Then I reinstalled Meteor by using
`curl https://install.meteor.com/ | sh`

Again did **meteor update** at project folder. Nothing is working. 
**mup deploy** is still hanging.  **mup setup** is successful.

How should I resolve this hanging problem?

**Comment by zodern** [comment] 2017-03-12 18:25
At what step is it hanging?

**Comment by ivanthemeh** [comment] 2017-03-12 18:35
@zodern I got it working, Im guessing I have to set up the letsencrypt myself?

**Comment by iAssureIT** [comment] 2017-03-12 18:58
It is hanging when I try to execute command of 
**mup deploy**

Then it says.. 
**`Building App Bundle Locally`**

And then it hangs forever...   It tried it 10+ times.. but everytime it is hanging. 

Ideally, some output should come after every couple of seconds, to indicate something is happening during deploy. It would be great if some progress bar is shown while "mup deploy" is getting executed. 
Because, we are working on some large scale enterprise apps in Meteor. These apps may take a while to get build and deploy. Before deploy process ends, our PuTTy SSH connection is also getting timed out. 
Again we have to login and again we have to issue **mup setup**  and **mup deploy** commands. 
Again we face the same hanging issue.

**Comment by zodern** [comment] 2017-03-13 14:17
@iAssureIT I just released 1.2.4. Update mup with `npm install -g mup`, and try deploying with `mup deploy --verbose`. With the verbose flag it will show the output from `meteor build`

**Comment by iAssureIT** [comment] 2017-03-14 04:03
Thanks @zodern ! 
I reinstalled mup 1.2.4. Also reinstalled node & npm. 
Cleaned up all other PIDs related to docker. Then tried to deploy both projects again one by one. 

**mup setup**  (Successful for both apps)
**mup deploy --verbose**   (My App1 is working fine. But 2nd App is showing error message as follows) 
App#2 has following error

```
 mup deploy --verbose
Building App Bundle Locally

=> Build Error. Check the logs printed above.
(node:6447) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: build-error
(node:6447) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**This is the error I am getting from beginning.** 

Here is my App#2 mup.js
```
module.exports = {
  servers: {
    one: {
      host: '35.164.201.159',
      username: 'ubuntu',
      pem: '~/.ssh/iAssureIT-Ubuntu.pem',
      // password:
      // or leave blank for authenticate from ssh-agent
    }
  },

  meteor: {
    name: 'musissive',
    path: '/var/www/meteor/musissive',
    servers: {
      one: {},
    },
    buildOptions: {
      serverOnly: true,
    },
    env: {
      ROOT_URL: 'http://musissive.in',
      MONGO_URL: 'mongodb://localhost/meteor',
      PORT: 3003,
    },


    docker: {
      // change to 'kadirahq/meteord' if your app is not using Meteor 1.4
      image: 'abernix/meteord:base',
    },
    deployCheckWaitTime: 60,

    // Show progress bar while uploading bundle to server
    // You might need to disable it on CI servers
    enableUploadProgressBar: false
  },

  mongo: {
    oplog: true,
    port: 27017,
     version: '3.4.1',
    servers: {
      one: {},
    },
  },
};
```

**How to resolve this error?  I need to run multiple apps on single ubuntu server.**

**Comment by iAssureIT** [comment] 2017-03-14 06:55
@zodern, I stopped App#1 and now wanted to see if App#2 is working individually. 
So I issued command **mup stop** to close app#1. 
in app#2 folder, I did **mup setup** and **mup deploy --verbose**
it got stuck after showing the downloading meteor-tool as follows. 

```
mup deploy --verbose
Building App Bundle Locally
   Downloading meteor-tool@1.4.2_7...
```

It got stuck at this place for long time... more often, we lost the connection due to timeout in PuTTy SSH connection. 
Can **mup** provide a progress bar at this step?

**Comment by zodern** [comment] 2017-03-14 14:23
Are you able to run app#2 locally?

**Comment by iAssureIT** [comment] 2017-03-14 18:11
Yes, App#2 is working perfectly fine on Development Ubuntu environment. 
Here are the output that I am getting for mup setup & deploy commands. 

**It is failing in mup deploy step. Not understanding what is this error and how to resolve this.** 

```
ubuntu@ip-172-31-19-8:/var/www/meteor/musissive/.deploy$ mup setup

Started TaskList: Setup Docker
[54.218.35.182] - setup docker
[54.218.35.182] - setup docker: SUCCESS

Started TaskList: Setup Meteor
[54.218.35.182] - Setup Environment

Started TaskList: Setup Mongo
[54.218.35.182] - setup environment
[54.218.35.182] - setup environment: SUCCESS
[54.218.35.182] - copying mongodb.conf
[54.218.35.182] - Setup Environment: SUCCESS
[54.218.35.182] - copying mongodb.conf: SUCCESS

Started TaskList: Start Mongo
[54.218.35.182] - start mongo
[54.218.35.182] - start mongo: SUCCESS

Next, you should run:
    mup deploy
ubuntu@ip-172-31-19-8:/var/www/meteor/musissive/.deploy$ mup deploy --verbose
Building App Bundle Locally
   Minifying app code
=> Build Error. Check the logs printed above.
Error: build-error
    at ChildProcess.<anonymous> (/usr/lib/node_modules/mup/lib/modules/meteor/build.js:46:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

```

**Comment by iAssureIT** [comment] 2017-03-14 18:53
@zodern, the important part to note is that when I run the app with **meteor** command, I can see the app working fine on my url. 
But when **mup deploy** command is issued, it is failing with above error.

**Comment by zodern** [comment] 2017-03-15 03:23
That's strange meteor build is exiting with an error code at that point in the build process.

Please try running `meteor build ../mup-build --architecture os.linux.x86_64 --server-only`
If that seems to run successfully, you can tell meteor up to use that build.
In your config, change `meteor.buildOptions.buildLocation` to `../mup-build` and run `mup deploy --cached-build`.

**Comment by iAssureIT** [comment] 2017-03-15 11:12
@zodern, GOOD NEWS!
All the above errors have gone, as soon as I increased the RAM size from 1GB to 4GB. 
Now MUP DEPLOY is working very fine. 
Thank you... Thank you... Thank you very much for all your help!

**Closed as completed** 2017-03-20 15:22 UTC
Labels: Bug
