### ISSUE TITLE
Deployment fails at Verifying Deployment (error from daemon in stream)

### ISSUE THREAD

**Issue by movationdesign** [zodern/meteor-up#886] opened 2018-02-20 15:59 UTC
Deployment keeps failing at the very last step of deployment to a DigitalOcean Droplet. I've redeployed at least 15 times over the past 5 hours. It doesn't appear to make any difference when I switch up the settings in the mup.js file, I get the same error each time.

[67.205.154.217] - Start Meteor
[67.205.154.217] - Start Meteor: SUCCESS
[67.205.154.217] - Verifying Deployment
[67.205.154.217] x Verifying Deployment: FAILED

Followed by this STDERR
------------------------------------STDERR—————————————————— 
Too much time spent restarting. error from daemon in stream: 
Error grabbing logs: EOF => 
Redeploying previous version of the app 
------------------------------------STDOUT—————————————————— 

To see more logs type 'mup logs --tail=200'

By the way, nothing happens when I type 'mup logs —tail=200’  — shouldn't I get a log file returned?

**My Setup:**
Macbook pro
THe Meteor (v 1.6) app is based on the VulcanJS framework (http://docs.vulcanjs.org/deployment.html)
I deploy to a DigitalOcean droplet using the latest Mup version
I connect via SSH
All npm packages are up to date
Ubuntu 16.04.3 x64
Nginx
Let's Encrypt (SSL)

In the mup.js file I've tried switching up the docker image version numerous times, this is the last one I tried: image: 'abernix/meteord:node-8.9.1-base'

I've also increased the deployCheckWaitTime up to 300s. 

I've destroyed and rebuild my Droplet and reinstalled everything twice before writing this message. 

I've also resized my Droplet (moving from 1GB ram to 2GB) in case it wasn't powerful enough, but that made no difference. 

Any suggestions? :-)

**Comment by zodern** [comment] 2018-02-20 16:34
This is a duplicate of #883. Could you please run `mup deploy --verbose` and paste the output after `Verifying Deployment` in that issue?

**Closed as completed by zodern** 2018-02-20 16:34 UTC
