### ISSUE TITLE
Per server env configuration

### ISSUE THREAD

**Issue by clayne11** [zodern/meteor-up#313] opened 2016-09-28 03:44 UTC
We need to be able to set an environment configuration per server. This is necessary for `cluster`. The old `mupx` set the `CLUSTER_ENDPOINT_URL` automatically however this is no longer happening and so we need per server environment configuration.

**Comment by elie222** [comment] 2016-10-05 13:58
I agree. There's a PR for this here:
https://github.com/kadirahq/meteor-up/pull/248

**Comment by jamesgibson14** [comment] 2016-10-21 14:36
1+

**Comment by zodern** [comment] 2017-02-11 19:23
Duplicate of #244

**Closed as completed by zodern** 2017-02-11 19:23 UTC
